# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/quantity_db
spring.datasource.username=postgres
spring.datasource.password=000

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Ensure the driver is explicitly mentioned
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081